

BEGIN TRAN

DELETE FROM KP_SYSTEM_PARAMETERS
DELETE FROM KP_KEY_PRESS_COUNT
DELETE FROM KP_EVENT_KEY_CHAR
DELETE FROM KP_EVENT_KEY_ALL
DELETE FROM KP_EVENT_MOUSE
DELETE FROM KP_MISTAKE_CHAR
DELETE FROM KP_WINDOWS

COMMIT TRAN